apiVersion: v1
kind: Service
metadata:
  name: opspilot-service
  namespace: opspilot
spec:
  type: NodePort
  selector:
    app: opspilot
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32545